ToolbarsExplorer 1.5 dev and stable
nvaccess/addonFiles pull request #143
Opened 2021-07-26 15:18 UTC by ABuffEr

### Release information

- Name: ToolbarsExplorer
- Author: Alberto Buffolino
- Repo: https://github.com/ABuffEr/toolbarsExplorer
- Version: 1.5
- Update channel: stable and dev
- NVDA compatibility: from 2017.3 to 2021.1

### Changelog

- Compatibility changes for 2021.1
- Fixes for browsers and other applications
- New naming convention for dev versions (yyyymmdd-dev)

### Additional information

Readme already links to official website (keys "tbx" and "tbx-dev").

1.4 stable is very old, and I unofficially released dev versions (with a naming convention not so clear) for a long time; so, I included here the new stable and a dev version generated with "scons dev=1", to provide a compatible/updated version for all channels/users.

2021-07-27 05:50 UTC, nvdaes requested changes
@ABuffEr , can you check if the stable add-on, internally, is the same as the dev add-on? Seems that, despite the different names, the manifest.ini is the same for stable and dev.

2021-07-27 11:26 UTC, ABuffEr commented
Hi @nvdaes ,
sorry, I played with scons dev yesterday for first time, and I not noticed that I must run scons --clean to force scons to read again from buildVars (with stable version and channel).
Fixed now.

2021-07-27 12:38 UTC, nvdaes approved these changes
Thanks for fixing this.

2021-07-29 06:51 UTC, feerrenrut approved these changes

2021-07-29 06:51 UTC, merged