easyTableNavigator 2.2
nvaccess/addonFiles pull request #158
Opened 2021-08-23 15:58 UTC by Oreonan

### Release information
- Name (Example, Add-on Updater): 
easyTableNavigator
- Author (example, Your Name): 
Corentin Bacqué-Cazenave
- Repo (example, https://github.com/yourname/addonName): 
https://github.com/Oreonan/easyTableNavigator-1
- Version (example, 21.07): 
2.2
- Update channel (example, stable, dev or stable and dev): 
stable and dev
- NVDA compatibility (example, 2021.1 and beyond): 
2019.3 to 2021.1

### Changelog (mention changes in separate lines starting with dash space)
## Changes for 2.2

* Update documentation style from addons template
* First translated version

### Additional information

2021-08-24 06:19 UTC, nvdaes reviewed
@Oreonan, we have to review the url and manifest. So, I suggest you to attach the binary on a GitHub release for ease of review. Also, I would mention @josephsl as an author, though he is not currently a maintainer, but he's the first creator of this add-on, and the template for PRs against this repo, at this moment, suggest to mention authors, not maintainers. Just for reference.
Thanks

2021-08-24 06:57 UTC, Oreonan commented
I've added @josephsl to authors, sorry, I forgot to add him yesterday...
The release with binary can be find here:
https://github.com/Oreonan/easyTableNavigator-1/releases/tag/v2.2

2021-08-24 07:16 UTC, nvdaes requested changes
Thanks. Can you use the GitHub URL instead of binaries?

2021-08-24 07:16 UTC, nvdaes commented on get.php
> +	"etn" => "easyTableNavigator-2.2.nvda-addon",
```suggestion
	"etn" => "https://github.com/Oreonan/easyTableNavigator-1/releases/download/v2.2/easyTableNavigator-2.2.nvda-addon",
```

2021-08-24 07:16 UTC, nvdaes commented on get.php
> +	"etn-dev" => "easyTableNavigator-2.2.nvda-addon",
```suggestion
	"etn-dev" => "https://github.com/Oreonan/easyTableNavigator-1/releases/download/v2.2/easyTableNavigator-2.2.nvda-addon",
```

2021-08-24 08:10 UTC, nvdaes approved these changes
Thanks. I advice, instead of claiming for NVDA compatibility, in the add-on documentation, from 2019.3 to 2021.1, reflect: 2019.3 and beyond, since this will be compatible with 2021.2 and later versions

2021-08-24 08:13 UTC, nvdaes commented
I closed this accidentally, then reopened awaiting a review from @feerrenrut

2021-08-25 05:35 UTC, feerrenrut approved these changes

2021-08-25 05:36 UTC, merged